# Generated by Django 5.0 on 2023-12-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_sharing', '0002_alter_secret_created_at_alter_secret_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='content',
            field=models.TextField(max_length=560),
        ),
    ]
