# Generated by Django 5.0 on 2023-12-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_sharing', '0003_alter_secret_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
