# Generated by Django 5.0 on 2023-12-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_sharing', '0005_secret_upvote_count_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
