# Generated by Django 5.0 on 2023-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_sharing', '0006_vote_created_at_vote_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='user',
            new_name='author',
        ),
    ]
